
server:
  port: 8081

spring:
  datasource:
      url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
      username: c##q1
      password: q1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect

